version: "3"
services:
  hotspot-monitoring-app:
    container_name: hotspot-monitoring-app
    build: .
    ports:
      - "8900:8900"
    links:
      - hotspot-mongo-db
  hotspot-mongo-db:
    container_name: hotspot-mongo-db
    ports:
      - "27017:27017"
    image: mongo
    volumes:
      - ./data:/data/db